dbt_medallion:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: oauth
      project: your-gcp-project-id
      dataset: dev_dataset
      threads: 4
      location: US
      priority: interactive
    staging:
      type: bigquery
      method: oauth
      project: your-gcp-project-id
      dataset: staging_dataset
      threads: 4
      location: US
      priority: batch
    prod:
      type: bigquery
      method: oauth
      project: your-gcp-project-id
      dataset: prod_dataset
      threads: 4
      location: US
      priority: batch