dbt_medallion:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: oauth
      project: project-2ac71b10-d4cb-403a-b2c
      dataset: dev_dataset
      threads: 4
      location: us-east5
      priority: interactive
    staging:
      type: bigquery
      method: oauth
      project: project-2ac71b10-d4cb-403a-b2c
      dataset: staging_dataset
      threads: 4
      location: us-east5
      priority: batch
    prod:
      type: bigquery
      method: oauth
      project: project-2ac71b10-d4cb-403a-b2c
      dataset: prod_dataset
      threads: 4
      location: us-east5
      priority: batch